### PR TITLE
Angular v9 update

### PR DESCRIPTION
**Pull request by albert5287**

### CODE REVIEW

**Comment by travist** [comment]
Thank you for this! I will commit this into a 2.x build of this library.

**Comment by StefanPostelnecu** [comment]
Hello,

Any news related the moment of release the 2.x build? 

Thanks
Stefan

**Comment by travist** [comment]
We will try to allocate some developers on this next week.

**Comment by light9** [comment]
Is any news regarding that issue?

**Comment by StefanPostelnecu** [comment]
Yes please give us feedback,  I am also very  interested in this subject.
Thanks
Stefan

**Comment by light9** [comment]
Thanks for update Stefan! I will check in on this week!

**Comment by gciochina** [comment]
@travist is there any news on this?

**Comment by travist** [comment]
I would probably rather skip version 9 at this point and move straight to 10. We are currently upgrading our angular-formio library to work with 10, so this would need to come after that.

**Comment by ClaudiuB-Cpi** [comment]
@travist That would be nice, is there any place where we can see the progress with Angular 10?

**Comment by BondocClaudiu** [comment]
@travist That would be nice, is there any place where we can see the progress with Angular 10?

**Comment by travist** [comment]
It is in the works right now so stay tuned.

**Comment by SAkhil95** [comment]
I am also interested to get the Mat Form.io up & running for Angular 10.
Thanks for the PR @albert5287 . Is there any update on this @travist ?

Also, for **angular-formio**, we have :: `Formio.createForm()`, don't we have something like : `matFormio.createForm()` in **angular-material-formio** ?

Thanks.

**Comment by travist** [comment]
Closing due to new release now supporting Angular 10 & 11.

**Pull request closed without merging**
